### ISSUE TITLE
whitelisting transip IPs

### ISSUE THREAD

**Issue by mfiers** [thijsbrilleman/dynamic-ip-transip-automatic-update#2]
Hey, nice project!

It seems I need to whitelist my ip for API calls on the transip API page.

So I'm a little confused how, if my IP changes, can I still make the required API call to update my DNS?

thanks.M

**Comment by thijsbrilleman** [comment]
You can disable the use of a whitelist when you create a specific keypair on the Transip API control panel page.

Just uncheck "Accepteer alleen IP-addressen uit de whitelist"
